version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=springdb
    ports:
      - "3306:3306"

  timesheet-app:
    image: bouhajaomar/timesheet-app:latest
    container_name: timesheet-container
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/springdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
